Repository opendevstack/ods-quickstarters, pull requests merged in 2020-03, with the labels that each got.

#91 Add e2e-spock-geb quickstarter
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/e2e-spock-geb.adoc
  e2e-spock-geb/Jenkinsfile
  e2e-spock-geb/Jenkinsfile.template
  e2e-spock-geb/README.md
  e2e-spock-geb/files/.editorconfig
  e2e-spock-geb/files/build.gradle
  e2e-spock-geb/files/gradle/wrapper/gradle-wrapper.jar
  e2e-spock-geb/files/gradle/wrapper/gradle-wrapper.properties
  e2e-spock-geb/files/gradlew
  e2e-spock-geb/files/gradlew.bat
  e2e-spock-geb/files/metadata.yml
  e2e-spock-geb/files/src/test/acceptance/groovy/.gitkeep
  e2e-spock-geb/files/src/test/acceptance/groovy/DemoAcceptanceSpec.groovy
  e2e-spock-geb/files/src/test/acceptance/java/.gitkeep
  e2e-spock-geb/files/src/test/acceptance/java/DemoAcceptanceTest.java
  e2e-spock-geb/files/src/test/installation/groovy/DemoInstallationSpec.groovy
  e2e-spock-geb/files/src/test/installation/java/.gitkeep
  e2e-spock-geb/files/src/test/installation/java/DemoInstallationTest.java
  e2e-spock-geb/files/src/test/integration/groovy/DemoIntegrationSpec.groovy
  e2e-spock-geb/files/src/test/integration/java/.gitkeep
  e2e-spock-geb/files/src/test/integration/java/DemoIntegrationTest.java
  e2e-spock-geb/files/src/test/resources/GebConfig.groovy
  e2e-spock-geb/files/src/test/resources/SpecHelper.groovy
  e2e-spock-geb/files/src/test/resources/application.properties
  e2e-spock-geb/sonar-project.properties
Labels: enhancement

#152 add gunicorn and restructure test suite for be-python-flask
  be-python-flask/Jenkinsfile
  be-python-flask/Jenkinsfile.template
  be-python-flask/files/.coveragerc
  be-python-flask/files/docker/Dockerfile
  be-python-flask/files/docker/run.sh
  be-python-flask/files/mypy.ini
  be-python-flask/files/src/app.py
  be-python-flask/files/src/main.py
  be-python-flask/files/src/requirements.txt
  be-python-flask/files/src/static/css/main.css
  be-python-flask/files/src/static/img/bix.jpg
  be-python-flask/files/src/templates/base.html
  be-python-flask/files/src/test_requirements.txt
  be-python-flask/files/src/tests/tests.py
  be-python-flask/files/tests/__init__.py
  be-python-flask/files/tests/main_test.py
  be-python-flask/files/tests/pytest.ini
  be-python-flask/files/tests/requirements.txt
  be-python-flask/sonar-project.properties.template
  common/jenkins-slaves/python/Dockerfile.rhel7
  common/jenkins-slaves/python/README.md
  docs/modules/ROOT/pages/be-python-flask.adoc
Labels: documentation, enhancement

#157 Add env var releaseStatusJiraIssueKey for e2e-spock-geb
  release-manager/ocp-config/cd-pipeline.yml
Labels: enhancement

#156 Add OS project and cluster public host to env for e2e-spock-geb
  e2e-spock-geb/Jenkinsfile.template
  e2e-spock-geb/files/src/test/resources/GebConfig.groovy
  e2e-spock-geb/files/src/test/resources/SpecHelper.groovy
Labels: enhancement

#155 Add test-logger plugin for e2e-spock-geb
  e2e-spock-geb/files/build.gradle
Labels: enhancement

#176 fix ds-rshiny bc resources and deps
  ds-rshiny/Jenkinsfile
  ds-rshiny/files/docker/Dockerfile
Labels: bug

#177 fix ds-rshiny bc resources and deps
  ds-rshiny/Jenkinsfile
  ds-rshiny/files/docker/Dockerfile
Labels: bug

#186 remove junit from quickstarter - 2.x
  be-golang-plain/Jenkinsfile.template
Labels: enhancement

#207 fix non required try in fe-angular
  fe-angular/Jenkinsfile.template
Labels: bug

#208 fix non required try in fe-angular
  fe-angular/Jenkinsfile.template
Labels: bug
