Repository opendevstack/ods-quickstarters, pull requests merged in 2020-12, with the labels that each got.

#510 Add UBI8 variant for Python agent image
  .github/workflows/continuous-integration-workflow.yml
  common/jenkins-agents/python/docker/Dockerfile.rhel7
  common/jenkins-agents/python/docker/Dockerfile.ubi8
  common/jenkins-agents/python/ocp-config/bc.yml
Labels: openshift4

#507 Remove empty build triggers
  be-fe-mono-repo-plain/openshift/component-template.yml
  common/jenkins-agents/golang/ocp-config/bc.yml
  common/jenkins-agents/maven/ocp-config/bc.yml
  common/jenkins-agents/nodejs12/ocp-config/bc.yml
  common/jenkins-agents/python/ocp-config/bc.yml
  common/jenkins-agents/scala/ocp-config/bc.yml
  common/ocp-config/component-environment/component-template.yml
  common/ocp-config/component/template.yml
  common/ocp-config/ds-component-environment/ds-component.yml
  ds-ml-service/openshift/component-template.yml
Labels: openshift4

#508 Remove empty build triggers (3.x)
  be-fe-mono-repo-plain/openshift/component-template.yml
  common/jenkins-agents/golang/ocp-config/bc.yml
  common/jenkins-agents/maven/ocp-config/bc.yml
  common/jenkins-agents/nodejs10-angular/ocp-config/bc.yml
  common/jenkins-agents/python/ocp-config/bc.yml
  common/jenkins-agents/scala/ocp-config/bc.yml
  common/ocp-config/component-environment/component-template.yml
  common/ocp-config/ds-component-environment/ds-component.yml
  ds-ml-service/openshift/component-template.yml
Labels: openshift4

#509 change maven version for maven-agent rhel7
  .github/workflows/continuous-integration-workflow.yml
  common/jenkins-agents/maven/docker/Dockerfile.rhel7
Labels: breaking change

#511 Add UBI8 variant for Scala agent image
  common/jenkins-agents/scala/docker/Dockerfile.rhel7
  common/jenkins-agents/scala/docker/Dockerfile.ubi8
  common/jenkins-agents/scala/ocp-config/bc.yml
Labels: openshift4

#514 Read more environment variables for the QS pipeline
  be-fe-mono-repo-plain/Jenkinsfile
  be-gateway-nginx/Jenkinsfile
  be-golang-plain/Jenkinsfile
  be-java-springboot/Jenkinsfile
  be-python-flask/Jenkinsfile
  be-scala-play/Jenkinsfile
  be-typescript-express/Jenkinsfile
  docker-plain/Jenkinsfile
  ds-jupyter-notebook/Jenkinsfile
  ds-ml-service/Jenkinsfile
  ds-rshiny/Jenkinsfile
  e2e-cypress/Jenkinsfile
  e2e-spock-geb/Jenkinsfile
  fe-angular/Jenkinsfile
  fe-ionic/Jenkinsfile
  ods-document-gen-svc/Jenkinsfile
  ods-provisioning-app/Jenkinsfile
  release-manager/Jenkinsfile
Labels: enhancement

#516 Fix quickstarters
  be-fe-mono-repo-plain/Jenkinsfile.template
  ds-jupyter-notebook/Jenkinsfile.template
  ds-jupyter-notebook/testdata/golden/jenkins-build-stages.json
  ds-ml-service/Jenkinsfile.template
  ds-ml-service/openshift/component-template.yml
  ds-rshiny/Jenkinsfile.template
  ds-rshiny/testdata/golden/jenkins-build-stages.json
Labels: bug

#519 Fix expected stage name
  ds-ml-service/testdata/golden/jenkins-build-stages.json
Labels: bug

#521 Do not run yum makecache
  common/jenkins-agents/nodejs12/docker/Dockerfile.rhel7
Labels: bug

#523 Adjust rollout data
  be-fe-mono-repo-plain/Jenkinsfile.template
  ds-ml-service/Jenkinsfile.template
Labels: enhancement

#527 Add example using env vars from Jenkinsfile to application.properties in Spock/Geb quickstarter
  e2e-spock-geb/files/src/test/resources/application.properties
Labels: enhancement
