Repository opendevstack/ods-quickstarters, pull requests merged in 2020-05, with the labels that each got.

#268 Improve quickstarter documentation
  common/jenkins-slaves/airflow/README.md
  common/jenkins-slaves/maven/README.md
  common/jenkins-slaves/nodejs10-angular/README.md
  common/jenkins-slaves/python/README.md
  common/jenkins-slaves/scala/README.md
  docs/modules/jenkins-slaves/pages/__JENKINS_SLAVE_TEMPLATE.adoc
  docs/modules/jenkins-slaves/pages/airflow.adoc
  docs/modules/jenkins-slaves/pages/golang.adoc
  docs/modules/jenkins-slaves/pages/maven.adoc
  docs/modules/jenkins-slaves/pages/nodejs10-angular.adoc
  docs/modules/jenkins-slaves/pages/python.adoc
  docs/modules/jenkins-slaves/pages/scala.adoc
  docs/modules/quickstarters/nav.adoc
  docs/modules/quickstarters/pages/__JENKINS_SLAVE_TEMPLATE_README.adoc
  docs/modules/quickstarters/pages/__QS_BOILERPLATE_TEMPLATE_README.adoc
  docs/modules/quickstarters/pages/__QUICKSTARTER_TEMPLATE.adoc
  docs/modules/quickstarters/pages/authoring-quickstarters.adoc
  docs/modules/quickstarters/pages/index.adoc
Labels: documentation

#260 WIP: Add gcc/g++ to support builds with CGO_ENABLED=1
  common/jenkins-slaves/golang/Dockerfile.rhel7
Labels: enhancement

#266 remove not required provisioning stage for airflow
  airflow-cluster/Jenkinsfile
Labels: bug

#281 Add glibc to the golang quick starter
  be-golang-plain/files/docker/Dockerfile
Labels: enhancement

#288 Add Go coverage report to SonarQube
  be-golang-plain/Jenkinsfile.template
  be-golang-plain/sonar-project.properties.template
Labels: enhancement

#293 add be-gateway-nginx adoc
  docs/modules/quickstarters/nav.adoc
  docs/modules/quickstarters/pages/be-gateway-nginx.adoc
Labels: documentation

#298 Fix link to xorg-x11-server-Xvfb package yet again
  common/jenkins-slaves/nodejs10-angular/Dockerfile.rhel7
Labels: bug

#300 Remove stage to create OpenShift resources
  e2e-cypress/Jenkinsfile
Labels: bug

#301 Remove Sonar properties stage
  e2e-cypress/Jenkinsfile
Labels: bug

#311 Fix release manager openshift resources
  release-manager/Jenkinsfile
  release-manager/create-ocp-resources.sh
  release-manager/ocp-config/cd-docgen.yml
  release-manager/ocp-config/cd-pipeline.yml
Labels: bug

#306 fix path to coverage analysis data
  fe-angular/sonar-project.properties.template
Labels: bug
