Repository opendevstack/ods-quickstarters, pull requests merged in 2020-07, with the labels that each got.

#353 ds-ml-service coverage via pytest and mlservice packaged
  ds-ml-service/Jenkinsfile.template
  ds-ml-service/files/build.bat
  ds-ml-service/files/build.sh
  ds-ml-service/files/docker/Dockerfile
  ds-ml-service/files/src/mlservice/__init__.py
  ds-ml-service/files/src/mlservice/model/__init__.py
  ds-ml-service/files/src/mlservice/model/data_cleaning/__init__.py
  ds-ml-service/files/src/mlservice/model/data_cleaning/replace.py
  ds-ml-service/files/src/mlservice/model/feature_prep/__init__.py
  ds-ml-service/files/src/mlservice/model/feature_prep/polynomial.py
  ds-ml-service/files/src/mlservice/model/model_wrapper.py
  ds-ml-service/files/src/mlservice/model/trainer.py
  ds-ml-service/files/src/mlservice/services/__init__.py
  ds-ml-service/files/src/mlservice/services/infrastructure/__init__.py
  ds-ml-service/files/src/mlservice/services/infrastructure/environment.py
  ds-ml-service/files/src/mlservice/services/infrastructure/flask.py
  ds-ml-service/files/src/mlservice/services/infrastructure/logging.py
  ds-ml-service/files/src/mlservice/services/infrastructure/remote/__init__.py
  ds-ml-service/files/src/mlservice/services/infrastructure/remote/dvc/__init__.py
  ds-ml-service/files/src/mlservice/services/infrastructure/remote/dvc/data_sync.py
  ds-ml-service/files/src/mlservice/services/infrastructure/remote/scripts/__init__.py
  ds-ml-service/files/src/mlservice/services/infrastructure/remote/scripts/remote_trainer.py
  ds-ml-service/files/src/mlservice/services/infrastructure/remote/ssh/__init__.py
  ds-ml-service/files/src/mlservice/services/infrastructure/remote/ssh/exceptions.py
  ds-ml-service/files/src/mlservice/services/infrastructure/remote/ssh/executors.py
  ds-ml-service/files/src/mlservice/services/prediction/__init__.py
  ds-ml-service/files/src/mlservice/services/prediction/app.py
  ds-ml-service/files/src/mlservice/services/training/__init__.py
  ds-ml-service/files/src/mlservice/services/training/app.py
  ds-ml-service/files/src/mlservice/services/training/templates/index.html
  ds-ml-service/files/src/run.sh
  ds-ml-service/files/test/integration_tests/services/prediction/test_prediction.py
  ds-ml-service/files/test/run_integration_tests.sh
  ds-ml-service/files/test/run_unittests.sh
  ds-ml-service/files/test/unittests/model/feature_prep/test_polynomial.py
  ds-ml-service/sonar-project.properties.template
Labels: enhancement

#357 Feature/quickstarter test frwrk
  tests/.gitignore
  tests/Makefile
  tests/be-typescript-express/golden/jenkins-build-stages.json
  tests/be-typescript-express/golden/jenkins-provision-stages.json
  tests/be-typescript-express/jenkinsfile_test.go
  tests/docker-plain/golden/jenkins-build-stages.json
  tests/docker-plain/golden/jenkins-provision-stages.json
  tests/docker-plain/jenkinsfile_test.go
  tests/go.mod
  tests/quickstarter-test.sh
  tests/scripts/print-jenkins-json-status.sh
  tests/scripts/print-jenkins-log.sh
  tests/test-setup/main.go
  tests/utils/apps.go
  tests/utils/builds.go
  tests/utils/cleanup-setup-tests.go
  tests/utils/images.go
  tests/utils/jenkinsfile.go
  tests/utils/resources.go
  tests/utils/services.go
  tests/utils/types.go
Labels: enhancement

#356 Select x86_64 architecture specifically
  common/jenkins-agents/maven/docker/Dockerfile
Labels: bug

#359 Feature/add sq test
  tests/be-typescript-express/golden/sonar-scan.json
  tests/be-typescript-express/jenkinsfile_test.go
  tests/docker-plain/jenkinsfile_test.go
  tests/scripts/print-sonar-scan-run.sh
  tests/utils/jenkinsfile.go
  tests/utils/sonarqube.go
Labels: enhancement

#358 Use new image import strategy if possible
  be-gateway-nginx/Jenkinsfile.template
  be-golang-plain/Jenkinsfile.template
  be-java-springboot/Jenkinsfile.template
  be-python-flask/Jenkinsfile.template
  be-scala-play/Jenkinsfile.template
  be-typescript-express/Jenkinsfile.template
  docker-plain/Jenkinsfile.template
  ds-jupyter-notebook/Jenkinsfile.template
  ds-rshiny/Jenkinsfile.template
  fe-angular/Jenkinsfile.template
  fe-ionic/Jenkinsfile.template
Labels: enhancement

#362 add exclusions to SonarQube coverage analysis
  docs/modules/quickstarters/pages/fe-angular.adoc
  docs/modules/quickstarters/pages/fe-ionic.adoc
  fe-angular/sonar-project.properties.template
  fe-ionic/sonar-project.properties.template
Labels: enhancement

#364 Feature/test getbuildname - dynamically from webhook proxy response
  tests/utils/jenkinsfile.go
Labels: enhancement

#369 Remove deprecated dockerImageRepository field
  be-fe-mono-repo-plain/openshift/component-template.yml
  common/jenkins-agents/golang/ocp-config/is.yml
  common/jenkins-agents/maven/ocp-config/is.yml
  common/jenkins-agents/nodejs10-angular/ocp-config/is.yml
  common/jenkins-agents/nodejs12/ocp-config/template.yaml
  common/jenkins-agents/python/ocp-config/is.yml
  common/jenkins-agents/scala/ocp-config/is.yml
  common/ocp-config/component-environment/component-template.yml
  common/ocp-config/ds-component-environment/ds-component.yml
  ds-ml-service/openshift/component-template.yml
Labels: bug

#381 fix some issues with fe-ionic
  fe-ionic/files/package.json
  fe-ionic/init.sh
Labels: bug

#393 Fix AMI pipeline
  tests/be-java-springboot/golden/sonar-scan.json
  tests/quickstarter-test.sh
  tests/utils/cleanup-setup-tests.go
Labels: enhancement

#390 add missing rm parameter and other missing pieces
  fe-ionic/files/tslint.json
  fe-ionic/init.sh
Labels: bug

#382 fe-ionic smoke tests
  tests/fe-ionic/golden/jenkins-build-stages.json
  tests/fe-ionic/golden/jenkins-provision-stages.json
  tests/fe-ionic/golden/sonar-scan.json
  tests/fe-ionic/jenkinsfile_test.go
Labels: enhancement

#391 Feature/document tests and also add RM quickstarter test thru prov app
  be-fe-mono-repo-plain/README.md
  be-gateway-nginx/README.md
  be-golang-plain/README.md
  be-java-springboot/README.md
  be-python-flask/README.md
  be-scala-play/README.md
  be-typescript-express/README.md
  common/scripts/README.md
  docker-plain/README.md
  ds-jupyter-notebook/README.md
  ds-ml-service/README.md
  ds-rshiny/README.md
  e2e-cypress/README.md
  e2e-spock-geb/README.md
  fe-angular/README.md
  fe-ionic/README.md
  tests/.gitignore
  tests/README.md
  tests/release-manager/golden/create-quickstarter-request.json
  tests/release-manager/golden/create-quickstarter-response.json
  tests/release-manager/golden/jenkins-build-stages-after-provisioning.json
  tests/release-manager/jenkinsfile_test.go
  tests/scripts/create-project-api.sh
  tests/scripts/delete-bitbucket-repo.sh
  tests/utils/jenkinsfile.go
Labels: enhancement

#395 Add docgen smoketests
  tests/ods-document-gen-svc/golden/jenkins-build-stages.json
  tests/ods-document-gen-svc/golden/jenkins-provision-stages.json
  tests/ods-document-gen-svc/golden/sonar-scan.json
  tests/ods-document-gen-svc/jenkinsfile_test.go
  tests/scripts/print-jenkins-json-status.sh
Labels: enhancement

#400 extend docgen tests
  tests/ods-document-gen-svc/golden/jenkins-build-stages.json
  tests/ods-document-gen-svc/jenkinsfile_test.go
Labels: enhancement

#401 Improve prov app quickstarter
  ods-provisioning-app/Jenkinsfile
  tests/ods-provisioning-app/golden/jenkins-build-stages.json
  tests/ods-provisioning-app/golden/jenkins-provision-stages.json
  tests/ods-provisioning-app/golden/sonar-scan.json
  tests/ods-provisioning-app/jenkinsfile_test.go
Labels: enhancement

#404 Feature/add complex RM test features, and use doc downloading tests
  tests/release-manager/files/metadata.yml
  tests/release-manager/golden/create-quickstarter-request.json
  tests/release-manager/golden/golang-sonar-scan.json
  tests/release-manager/golden/jenkins-build-stages-with-added-repo.json
  tests/release-manager/jenkinsfile_test.go
  tests/scripts/get-artifact-from-jenkins-run.sh
  tests/scripts/upload-file-to-bitbucket.sh
  tests/utils/jenkinsfile.go
Labels: enhancement

#405 (TESTS) feature/check for documents attached to builds
  tests/be-golang-plain/jenkinsfile_test.go
  tests/be-java-springboot/jenkinsfile_test.go
  tests/be-python-flask/jenkinsfile_test.go
  tests/ods-provisioning-app/jenkinsfile_test.go
  tests/release-manager/jenkinsfile_test.go
  tests/utils/cleanup-setup-tests.go
  tests/utils/jenkinsfile.go
  tests/utils/sonarqube.go
Labels: enhancement

#412 Compile Go tests
  .github/workflows/continuous-integration-workflow.yml
  tests/be-fe-mono-repo-plain/jenkinsfile_test.go
  tests/be-golang-plain/jenkinsfile_test.go
  tests/be-java-springboot/jenkinsfile_test.go
  tests/be-python-flask/jenkinsfile_test.go
  tests/docker-plain/jenkinsfile_test.go
  tests/ds-ml-service/jenkinsfile_test.go
  tests/ods-document-gen-svc/jenkinsfile_test.go
  tests/ods-provisioning-app/jenkinsfile_test.go
  tests/release-manager/jenkinsfile_test.go
  tests/utils/jenkinsfile.go
  tests/utils/sonarqube.go
Labels: enhancement

#409 (Tests) Add unit test result verification
  tests/be-golang-plain/jenkinsfile_test.go
  tests/be-java-springboot/jenkinsfile_test.go
  tests/be-python-flask/jenkinsfile_test.go
  tests/be-scala-play/jenkinsfile_test.go
  tests/be-typescript-express/jenkinsfile_test.go
  tests/ds-ml-service/jenkinsfile_test.go
  tests/e2e-cypress/jenkinsfile_test.go
  tests/e2e-spock-geb/jenkinsfile_test.go
  tests/fe-angular/jenkinsfile_test.go
  tests/fe-ionic/jenkinsfile_test.go
  tests/ods-document-gen-svc/jenkinsfile_test.go
  tests/ods-provisioning-app/jenkinsfile_test.go
  tests/scripts/verify-jenkins-unittest-results.sh
Labels: enhancement

#416 Feature/python38 and deps upgrade for jenkins agent and quickstarters
  be-python-flask/files/docker/Dockerfile
  be-python-flask/files/docker/run.sh
  be-python-flask/files/metadata.yml
  be-python-flask/files/src/requirements.txt
  be-python-flask/files/tests/requirements.txt
  common/jenkins-agents/python/docker/Dockerfile
  docs/modules/jenkins-agents/pages/golang.adoc
  docs/modules/jenkins-agents/pages/maven.adoc
  docs/modules/jenkins-agents/pages/nodejs10-angular.adoc
  docs/modules/jenkins-agents/pages/python.adoc
  docs/modules/jenkins-agents/pages/scala.adoc
  docs/modules/jenkins-agents/partials/update-to-3x.adoc
  docs/modules/quickstarters/pages/be-python-flask.adoc
  docs/modules/quickstarters/pages/ds-jupyter-notebook.adoc
  docs/modules/quickstarters/pages/ds-ml-service.adoc
  ds-jupyter-notebook/files/docker/Dockerfile
  ds-jupyter-notebook/files/docker/requirements.txt
  ds-jupyter-notebook/files/metadata.yml
  ds-ml-service/Jenkinsfile.template
  ds-ml-service/files/docker/Dockerfile
  ds-ml-service/files/jenkinsfile_helper.py
  ds-ml-service/files/metadata.yml
  ds-ml-service/files/src/mlservice/model/model_wrapper.py
  ds-ml-service/files/src/requirements.txt
  ds-ml-service/openshift/component-template.yml
Labels: breaking change, documentation, enhancement
