Repository opendevstack/ods-quickstarters, pull requests merged in 2020-08, with the labels that each got.

#427 add check for 409 on bb project creation - par test
  tests/scripts/setup_bitbucket_test_project.sh
Labels: Tests

#432 Fix tests
  scripts/get-config-param.sh
  tests/go.mod
  tests/go.sum
  tests/quickstarter-test.sh
  tests/scripts/create-project-api.sh
Labels: bug

#440 Bump typescript version
  e2e-cypress/files/package.json
Labels: bug

#447 Add health check for Go quickstarter
  be-golang-plain/Jenkinsfile
  be-golang-plain/files/main.go
  common/ocp-config/component/Tailorfile
  common/ocp-config/component/template.yml
Labels: enhancement
