Repository opendevstack/ods-quickstarters, pull requests merged in 2021-04, with the labels that each got.

#564 added changelog enforcer as github action
  .github/workflows/changelog-enforcer.yml
Labels: documentation, skip changelog

#515 Add AWS Terraform Quickstarter
  .github/workflows/continuous-integration-workflow.yml
  CHANGELOG.md
  common/jenkins-agents/README.md
  common/jenkins-agents/terraform/docker/Dockerfile.rhel7
  common/jenkins-agents/terraform/docker/Dockerfile.ubi8
  common/jenkins-agents/terraform/docker/Gemfile
  common/jenkins-agents/terraform/docker/Gemfile.lock
  common/jenkins-agents/terraform/docker/README.md
  common/jenkins-agents/terraform/docker/python_requirements
  common/jenkins-agents/terraform/ocp-config/Tailorfile
  common/jenkins-agents/terraform/ocp-config/bc.yml
  common/jenkins-agents/terraform/ocp-config/is.yml
  inf-terraform-aws/Jenkinsfile
  inf-terraform-aws/Jenkinsfile.template
  inf-terraform-aws/README.md
  inf-terraform-aws/environment.yml.template
  inf-terraform-aws/files/.editorconfig
  inf-terraform-aws/files/.gitignore
  inf-terraform-aws/files/.pre-commit-config.yaml
  inf-terraform-aws/files/.rubocop.yml
  inf-terraform-aws/files/.ruby-version
  inf-terraform-aws/files/.terraform-version
  inf-terraform-aws/files/Gemfile
  inf-terraform-aws/files/Gemfile.lock
  inf-terraform-aws/files/Makefile
  inf-terraform-aws/files/Pipfile
  inf-terraform-aws/files/Pipfile.lock
  inf-terraform-aws/files/README.md
  inf-terraform-aws/files/backend.tf
  inf-terraform-aws/files/cfs3.json
  inf-terraform-aws/files/environments/dev.json
  inf-terraform-aws/files/environments/prod.json
  inf-terraform-aws/files/environments/test.json
  inf-terraform-aws/files/inputs2outputs.tf
  inf-terraform-aws/files/kitchen.yml
  inf-terraform-aws/files/lib/scripts/createstackoutputs2yml.sh
  inf-terraform-aws/files/main.tf
  inf-terraform-aws/files/metadata.yml
  inf-terraform-aws/files/outputs.tf
  inf-terraform-aws/files/random.tf
  inf-terraform-aws/files/release-manager.yml
  inf-terraform-aws/files/reports/install/.gitignore
  inf-terraform-aws/files/stackmodulesoutputs.tf
  inf-terraform-aws/files/terraform-data.tf
  inf-terraform-aws/files/test/fixtures/default/backend.tf
  inf-terraform-aws/files/test/fixtures/default/main.tf
  inf-terraform-aws/files/test/fixtures/default/moduleoutputs.tf
  inf-terraform-aws/files/test/fixtures/default/random.tf
  inf-terraform-aws/files/test/integration/default/controls/blueprints.rb
  inf-terraform-aws/files/test/integration/default/controls/default.rb
  inf-terraform-aws/files/test/integration/default/files/.gitkeep
  inf-terraform-aws/files/test/integration/default/inspec.yml
  inf-terraform-aws/files/test/integration/default/inspec.yml.tmpl
  inf-terraform-aws/files/test/integration/default/libraries/aws.rb
  inf-terraform-aws/files/test/integration/default/libraries/fixture_data.rb
  inf-terraform-aws/files/test/integration/default/libraries/terraform_data.rb
  inf-terraform-aws/files/variables.tf
  inf-terraform-aws/files/versions.tf
Labels: enhancement

#565 Add AWS Quickstarter for 3.x
  .github/workflows/continuous-integration-workflow.yml
  common/jenkins-agents/terraform/docker/Dockerfile.rhel7
  common/jenkins-agents/terraform/docker/Dockerfile.ubi8
  common/jenkins-agents/terraform/docker/Gemfile
  common/jenkins-agents/terraform/docker/Gemfile.lock
  common/jenkins-agents/terraform/docker/README.md
  common/jenkins-agents/terraform/docker/python_requirements
  common/jenkins-agents/terraform/ocp-config/Tailorfile
  common/jenkins-agents/terraform/ocp-config/bc.yml
  common/jenkins-agents/terraform/ocp-config/is.yml
  inf-terraform-aws/Jenkinsfile
  inf-terraform-aws/Jenkinsfile.template
  inf-terraform-aws/README.md
  inf-terraform-aws/environment.yml.template
  inf-terraform-aws/files/.editorconfig
  inf-terraform-aws/files/.gitignore
  inf-terraform-aws/files/.pre-commit-config.yaml
  inf-terraform-aws/files/.rubocop.yml
  inf-terraform-aws/files/.ruby-version
  inf-terraform-aws/files/.terraform-version
  inf-terraform-aws/files/Gemfile
  inf-terraform-aws/files/Gemfile.lock
  inf-terraform-aws/files/Makefile
  inf-terraform-aws/files/Pipfile
  inf-terraform-aws/files/Pipfile.lock
  inf-terraform-aws/files/README.md
  inf-terraform-aws/files/backend.tf
  inf-terraform-aws/files/cfs3.json
  inf-terraform-aws/files/environments/dev.json
  inf-terraform-aws/files/environments/prod.json
  inf-terraform-aws/files/environments/test.json
  inf-terraform-aws/files/inputs2outputs.tf
  inf-terraform-aws/files/kitchen.yml
  inf-terraform-aws/files/lib/scripts/createstackoutputs2yml.sh
  inf-terraform-aws/files/main.tf
  inf-terraform-aws/files/metadata.yml
  inf-terraform-aws/files/outputs.tf
  inf-terraform-aws/files/random.tf
  inf-terraform-aws/files/release-manager.yml
  inf-terraform-aws/files/reports/install/.gitignore
  inf-terraform-aws/files/stackmodulesoutputs.tf
  inf-terraform-aws/files/terraform-data.tf
  inf-terraform-aws/files/test/fixtures/default/backend.tf
  inf-terraform-aws/files/test/fixtures/default/main.tf
  inf-terraform-aws/files/test/fixtures/default/moduleoutputs.tf
  inf-terraform-aws/files/test/fixtures/default/random.tf
  inf-terraform-aws/files/test/integration/default/controls/blueprints.rb
  inf-terraform-aws/files/test/integration/default/controls/default.rb
  inf-terraform-aws/files/test/integration/default/files/.gitkeep
  inf-terraform-aws/files/test/integration/default/inspec.yml
  inf-terraform-aws/files/test/integration/default/inspec.yml.tmpl
  inf-terraform-aws/files/test/integration/default/libraries/aws.rb
  inf-terraform-aws/files/test/integration/default/libraries/fixture_data.rb
  inf-terraform-aws/files/test/integration/default/libraries/terraform_data.rb
  inf-terraform-aws/files/variables.tf
  inf-terraform-aws/files/versions.tf
Labels: enhancement

#576 Update CODEOWNERS
  CODEOWNERS
Labels: skip changelog
